export const AUTH_API = {
  // LOGIN: "login.php",
  LOGIN: "login/login.php",
  REGISTER: "register.php",
  LOG_OUT: "logout.php",
  FORGOT_PASSWORD: "forgotpassword.php",
  CHANGE_MT5_PASSWORD: "change_mt5_password.php",
  SEND_OTP_TWOFAC_AUTH: "send_otp_2fa.php",
  SEND_OTP_TWOFAC_UNLINK: "send_otp_2fa_unlink.php",
  RESET_PASSWORD: "reset_password.php",
  GET_COUNTRY: "get_country.php",
  SEND_OTP_REG: "send_otp_reg.php",
  SEND_OTP: "send_otp.php",
};

export const USER_API = {
  GET_DASHBOARD: "get_dashboard.php",
  USER_BALANCE_DATA: "get_user_bal_data.php",
  GET_USER_DATA: "get_users.php",
  MT5_ACCOUNT_LIST: "mt5_accounts_list.php",
  REGISTER_IB: "register_ib.php",
  UPDATE_MT5_NICKNAME: "update_mt5_nickname.php",
  GET_ADMIN_BANK_DETAILS: "get_admin_bank_details.php",
  DEPOSIT_FUNDS_ADD_WALLET_BAL_CASH: "deposit_funds_add_wallet_bal_cash.php",
  CHANGE_LOGINPASSWORD: "change_loginpassword.php",
  EKYC: "ekyc.php",
  GET_KYC: "get_ekyc.php",
  CHECK_MT5_ACC_BALANCE: "check_mt5_acc_balance.php",
  MT5_TO_WALLET: "mt5_to_wallet_api.php",
  GET_PARTNER_DASHBOARD: "get_partner_dashboard.php",
  LINK_AUTH_VERIFY: "link_auth_verify.php",
  UNLINK_AUTH_VERIFY: "unlink_auth_verify.php",
  LIST_GROUP: "list_group.php",
  SEND_OTP_EMAIL: "send_otp_email.php",
  GET_COUNTERY: "get_country.php",
  GET_SUPPORT_TICKET: "get_support_ticket.php",
  CREATE_SUPPORT_TICKET: "create_support_ticket.php",
  OPEN_SUPPORT_TICKETS: "open_support_ticket_list.php",
  OPEN_SUPPORT_TICKET_DETAILS: "details_open_support_ticket_list.php",
  ADD_REMARK_CREATE_SUPPORT_TICKET: "add_remark_create_support_ticket.php",
  GET_ALL_ORDER_REPORT_HISTORY: "all_get_order_report_history.php",
  MT5_TO_MT5_TRANSFER: "mt5_to_mt5_tranfer_api.php",
  GET_BANK_DETAILS: "get_bank.php",
  ADD_USER_BANK: "user_bank_add.php",
  WALLET_TO_MT5: "wallet_to_mt5_api.php",
  WITHDRAW_FUND_BY_CRYPTO: "withdrwa_fund_withdraw_crypto_api.php",
  WITHDRAW_FUNDS_ADD_WALLET_BAL: "withdraw_funds_add_wallet_bal.php",
  WITHDRAW_FUND_ADD_WALLET_BAL_CASH: "withdraws_funds_add_wallet_bal_cash.php",
  GENERATE_WALLECT_BINANCE: "generate_wallet_binance.php",
  GENERATE_WALLECT_ETHEREUM: "generate_wallet_ethereum.php",
  GENERATE_WALLECT_POLYGON: "generate_wallet_polygon.php",
  GENERATE_WALLECT_TRON: "generate_wallet_tron.php",
  WALLET_TRANS_TRC: "wallet_trans_trc.php",
  WALLET_TRANS_BEP: "wallet_trans_bep.php",
  GET_DISCOUNT: "get_discounts.php",
  REGISTER_OTP_VERIFY: "register_otp_verify.php",
  GET_IB_ALL_COMMISSION: "get_ib_all_comm_history.php",
  GET_IB_COMMISSION: "get_ib_comm.php",
  WITHDRAWS_IB_FUNDS_ADD_WALLET: "withdraws_ib_funds_add_wallet.php",
  ADD_DEPOSIT_BONUS: "add_deposit_bonus.php",
  GET_ACTIVE_USER_BONUS: "get_active_user_bonus.php",
  CANCEL_ACTIVE_BONUS: "cancel_active_bonus.php",
  DEPOSIT_FUNDS_ADD_WALLET_BAL: "deposit_funds_add_wallet_bal.php",
  OPEN_LIVE_ACCOUNT_ADD: "open_live_account_add.php",
  UPDATE_USER: "update_user.php",
  UPDATE_ONLY_EMAIL: "update_only_email.php",
  UPDATE_ONLY_MOBILE_NO: "update_only_mobileno.php",
  GET_REPORT_CLIENT_TRANSACTION: "get_report_client_transaction.php",
  GET_CLIENT_ACCOUNTS: "get_client_accounts.php",
};

export const PARTNER_DASHBOARD = {
  GET_PARTNER_DASHBOARD: "get_partner_dashboard.php",
  GET_REPORT_CLIENTS: "get_report_clients.php",
  GET_REPORT_REWARD_HISTORY: "get_report_reward_history.php",
  GET_REBATES_CLIENT: "get_rebates_client.php",
  GET_REBATES_HISTORY: "get_rebates_history.php",
};

export const USER_NOTIFICATION = {
  READ_NOTIFICATION: "read_user_notification.php",
  GET_NOTIFICATION: "get_user_notification.php",
};
